apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: teste
        ports:
        - containerPort: 8080
        