apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
- service.yaml

namespace: nodeapp

images:
- name: teste
  newName: blgianini/teste
  newTag: 3dc36b3de25270527565c92939b50350426e1665
